// Code generated by protoc-gen-go.
// source: general.proto
// DO NOT EDIT!

/*
Package LighterGRPC is a generated protocol buffer package.

It is generated from these files:
	general.proto
	initialzer.proto
	rgb_service.proto
	system.proto

It has these top-level messages:
	Confirmation
	Empty
	Request
	ServiceTypeMessage
	ColorMessage
	StateMessage
	ScheduledSwitch
	LogEntry
	LogRequest
	ServerConfiguration
	ChangeParameterMessage
	FadeTime
	IPVersion
	Pins
	BackendVersion
*/
package LighterGRPC

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Confirmation struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *Confirmation) Reset()                    { *m = Confirmation{} }
func (m *Confirmation) String() string            { return proto.CompactTextString(m) }
func (*Confirmation) ProtoMessage()               {}
func (*Confirmation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Confirmation) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Empty message for Requests without any params
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Request struct {
	DeviceID string `protobuf:"bytes,1,opt,name=deviceID" json:"deviceID,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func init() {
	proto.RegisterType((*Confirmation)(nil), "LighterGRPC.Confirmation")
	proto.RegisterType((*Empty)(nil), "LighterGRPC.Empty")
	proto.RegisterType((*Request)(nil), "LighterGRPC.Request")
}

func init() { proto.RegisterFile("general.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4f, 0xcd, 0x4b,
	0x2d, 0x4a, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xf6, 0xc9, 0x4c, 0xcf, 0x28,
	0x49, 0x2d, 0x72, 0x0f, 0x0a, 0x70, 0x56, 0xd2, 0xe0, 0xe2, 0x71, 0xce, 0xcf, 0x4b, 0xcb, 0x2c,
	0xca, 0x4d, 0x2c, 0xc9, 0xcc, 0xcf, 0x13, 0x92, 0xe0, 0x62, 0x2f, 0x2e, 0x4d, 0x4e, 0x4e, 0x2d,
	0x2e, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x08, 0x82, 0x71, 0x95, 0xd8, 0xb9, 0x58, 0x5d, 0x73,
	0x0b, 0x4a, 0x2a, 0x95, 0x54, 0xb9, 0xd8, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4,
	0xb8, 0x38, 0x52, 0x52, 0xcb, 0x32, 0x93, 0x53, 0x3d, 0x5d, 0xc0, 0xca, 0x39, 0x83, 0xe0, 0x7c,
	0x27, 0x51, 0x2e, 0xc1, 0x94, 0x54, 0xbd, 0x82, 0xcc, 0x1c, 0x90, 0x6d, 0xc5, 0x10, 0xbb, 0x03,
	0x18, 0x93, 0xd8, 0xc0, 0x0c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x6b, 0x5f, 0x4d,
	0x95, 0x00, 0x00, 0x00,
}
