// Code generated by protoc-gen-go.
// source: lighter.proto
// DO NOT EDIT!

package LighterGRPC

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LogLevel int32

const (
	LogLevel_DEBUG LogLevel = 0
	LogLevel_INFO  LogLevel = 1
	LogLevel_WARN  LogLevel = 2
	LogLevel_ERROR LogLevel = 3
	LogLevel_PANIC LogLevel = 4
)

var LogLevel_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "WARN",
	3: "ERROR",
	4: "PANIC",
}
var LogLevel_value = map[string]int32{
	"DEBUG": 0,
	"INFO":  1,
	"WARN":  2,
	"ERROR": 3,
	"PANIC": 4,
}

func (x LogLevel) String() string {
	return proto.EnumName(LogLevel_name, int32(x))
}
func (LogLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type ColorMessage struct {
	Onstate  bool   `protobuf:"varint,1,opt,name=onstate" json:"onstate,omitempty"`
	R        int32  `protobuf:"varint,2,opt,name=r" json:"r,omitempty"`
	G        int32  `protobuf:"varint,3,opt,name=g" json:"g,omitempty"`
	B        int32  `protobuf:"varint,4,opt,name=b" json:"b,omitempty"`
	Opacity  int32  `protobuf:"varint,5,opt,name=opacity" json:"opacity,omitempty"`
	DeviceID string `protobuf:"bytes,6,opt,name=deviceID" json:"deviceID,omitempty"`
	Password string `protobuf:"bytes,7,opt,name=password" json:"password,omitempty"`
}

func (m *ColorMessage) Reset()                    { *m = ColorMessage{} }
func (m *ColorMessage) String() string            { return proto.CompactTextString(m) }
func (*ColorMessage) ProtoMessage()               {}
func (*ColorMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ColorMessage) GetOnstate() bool {
	if m != nil {
		return m.Onstate
	}
	return false
}

func (m *ColorMessage) GetR() int32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *ColorMessage) GetG() int32 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *ColorMessage) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *ColorMessage) GetOpacity() int32 {
	if m != nil {
		return m.Opacity
	}
	return 0
}

func (m *ColorMessage) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *ColorMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type StateMessage struct {
	Onstate  bool   `protobuf:"varint,1,opt,name=onstate" json:"onstate,omitempty"`
	DeviceID string `protobuf:"bytes,2,opt,name=deviceID" json:"deviceID,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *StateMessage) Reset()                    { *m = StateMessage{} }
func (m *StateMessage) String() string            { return proto.CompactTextString(m) }
func (*StateMessage) ProtoMessage()               {}
func (*StateMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *StateMessage) GetOnstate() bool {
	if m != nil {
		return m.Onstate
	}
	return false
}

func (m *StateMessage) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *StateMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ScheduledSwitch struct {
	Time     int64  `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Onstate  bool   `protobuf:"varint,2,opt,name=onstate" json:"onstate,omitempty"`
	DeviceID string `protobuf:"bytes,3,opt,name=deviceID" json:"deviceID,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
}

func (m *ScheduledSwitch) Reset()                    { *m = ScheduledSwitch{} }
func (m *ScheduledSwitch) String() string            { return proto.CompactTextString(m) }
func (*ScheduledSwitch) ProtoMessage()               {}
func (*ScheduledSwitch) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *ScheduledSwitch) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *ScheduledSwitch) GetOnstate() bool {
	if m != nil {
		return m.Onstate
	}
	return false
}

func (m *ScheduledSwitch) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *ScheduledSwitch) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LogEntry struct {
	Time    int64  `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *LogEntry) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogEntry) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LogRequest struct {
	LogLevel LogLevel `protobuf:"varint,1,opt,name=logLevel,enum=LighterGRPC.LogLevel" json:"logLevel,omitempty"`
	Amount   int32    `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Password string   `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *LogRequest) Reset()                    { *m = LogRequest{} }
func (m *LogRequest) String() string            { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()               {}
func (*LogRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *LogRequest) GetLogLevel() LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return LogLevel_DEBUG
}

func (m *LogRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *LogRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*ColorMessage)(nil), "LighterGRPC.ColorMessage")
	proto.RegisterType((*StateMessage)(nil), "LighterGRPC.StateMessage")
	proto.RegisterType((*ScheduledSwitch)(nil), "LighterGRPC.ScheduledSwitch")
	proto.RegisterType((*LogEntry)(nil), "LighterGRPC.LogEntry")
	proto.RegisterType((*LogRequest)(nil), "LighterGRPC.LogRequest")
	proto.RegisterEnum("LighterGRPC.LogLevel", LogLevel_name, LogLevel_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Lighter service

type LighterClient interface {
	GetStatus(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ColorMessage, error)
	OpenStream(ctx context.Context, in *Request, opts ...grpc.CallOption) (Lighter_OpenStreamClient, error)
	LoadServerLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (Lighter_LoadServerLogClient, error)
	ScheduleSwitchState(ctx context.Context, in *ScheduledSwitch, opts ...grpc.CallOption) (*Confirmation, error)
	SetColor(ctx context.Context, in *ColorMessage, opts ...grpc.CallOption) (*Confirmation, error)
	SwitchState(ctx context.Context, in *StateMessage, opts ...grpc.CallOption) (*Confirmation, error)
}

type lighterClient struct {
	cc *grpc.ClientConn
}

func NewLighterClient(cc *grpc.ClientConn) LighterClient {
	return &lighterClient{cc}
}

func (c *lighterClient) GetStatus(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ColorMessage, error) {
	out := new(ColorMessage)
	err := grpc.Invoke(ctx, "/LighterGRPC.Lighter/GetStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lighterClient) OpenStream(ctx context.Context, in *Request, opts ...grpc.CallOption) (Lighter_OpenStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Lighter_serviceDesc.Streams[0], c.cc, "/LighterGRPC.Lighter/OpenStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &lighterOpenStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lighter_OpenStreamClient interface {
	Recv() (*ColorMessage, error)
	grpc.ClientStream
}

type lighterOpenStreamClient struct {
	grpc.ClientStream
}

func (x *lighterOpenStreamClient) Recv() (*ColorMessage, error) {
	m := new(ColorMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lighterClient) LoadServerLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (Lighter_LoadServerLogClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Lighter_serviceDesc.Streams[1], c.cc, "/LighterGRPC.Lighter/LoadServerLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &lighterLoadServerLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lighter_LoadServerLogClient interface {
	Recv() (*LogEntry, error)
	grpc.ClientStream
}

type lighterLoadServerLogClient struct {
	grpc.ClientStream
}

func (x *lighterLoadServerLogClient) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lighterClient) ScheduleSwitchState(ctx context.Context, in *ScheduledSwitch, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := grpc.Invoke(ctx, "/LighterGRPC.Lighter/ScheduleSwitchState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lighterClient) SetColor(ctx context.Context, in *ColorMessage, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := grpc.Invoke(ctx, "/LighterGRPC.Lighter/SetColor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lighterClient) SwitchState(ctx context.Context, in *StateMessage, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := grpc.Invoke(ctx, "/LighterGRPC.Lighter/SwitchState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Lighter service

type LighterServer interface {
	GetStatus(context.Context, *Request) (*ColorMessage, error)
	OpenStream(*Request, Lighter_OpenStreamServer) error
	LoadServerLog(*LogRequest, Lighter_LoadServerLogServer) error
	ScheduleSwitchState(context.Context, *ScheduledSwitch) (*Confirmation, error)
	SetColor(context.Context, *ColorMessage) (*Confirmation, error)
	SwitchState(context.Context, *StateMessage) (*Confirmation, error)
}

func RegisterLighterServer(s *grpc.Server, srv LighterServer) {
	s.RegisterService(&_Lighter_serviceDesc, srv)
}

func _Lighter_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LighterServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LighterGRPC.Lighter/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LighterServer).GetStatus(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lighter_OpenStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LighterServer).OpenStream(m, &lighterOpenStreamServer{stream})
}

type Lighter_OpenStreamServer interface {
	Send(*ColorMessage) error
	grpc.ServerStream
}

type lighterOpenStreamServer struct {
	grpc.ServerStream
}

func (x *lighterOpenStreamServer) Send(m *ColorMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Lighter_LoadServerLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LighterServer).LoadServerLog(m, &lighterLoadServerLogServer{stream})
}

type Lighter_LoadServerLogServer interface {
	Send(*LogEntry) error
	grpc.ServerStream
}

type lighterLoadServerLogServer struct {
	grpc.ServerStream
}

func (x *lighterLoadServerLogServer) Send(m *LogEntry) error {
	return x.ServerStream.SendMsg(m)
}

func _Lighter_ScheduleSwitchState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduledSwitch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LighterServer).ScheduleSwitchState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LighterGRPC.Lighter/ScheduleSwitchState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LighterServer).ScheduleSwitchState(ctx, req.(*ScheduledSwitch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lighter_SetColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColorMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LighterServer).SetColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LighterGRPC.Lighter/SetColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LighterServer).SetColor(ctx, req.(*ColorMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lighter_SwitchState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LighterServer).SwitchState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LighterGRPC.Lighter/SwitchState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LighterServer).SwitchState(ctx, req.(*StateMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lighter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LighterGRPC.Lighter",
	HandlerType: (*LighterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Lighter_GetStatus_Handler,
		},
		{
			MethodName: "ScheduleSwitchState",
			Handler:    _Lighter_ScheduleSwitchState_Handler,
		},
		{
			MethodName: "SetColor",
			Handler:    _Lighter_SetColor_Handler,
		},
		{
			MethodName: "SwitchState",
			Handler:    _Lighter_SwitchState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenStream",
			Handler:       _Lighter_OpenStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LoadServerLog",
			Handler:       _Lighter_LoadServerLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lighter.proto",
}

func init() { proto.RegisterFile("lighter.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x8f, 0xd2, 0x40,
	0x14, 0x66, 0x28, 0x0b, 0xe5, 0x2d, 0x28, 0x8e, 0xae, 0x56, 0xe2, 0x81, 0xf4, 0x44, 0x3c, 0x90,
	0x75, 0xbd, 0x78, 0x72, 0xb3, 0xb0, 0x48, 0x48, 0x2a, 0x90, 0x69, 0x8c, 0x57, 0x0b, 0x7d, 0x96,
	0x26, 0xa5, 0x83, 0xd3, 0x01, 0xb2, 0xff, 0x8f, 0x47, 0xff, 0x48, 0xd3, 0x99, 0x76, 0x53, 0xd8,
	0x50, 0xe3, 0xed, 0x7d, 0xf3, 0xe6, 0xbd, 0xef, 0x7b, 0x3f, 0x66, 0xa0, 0x1d, 0x85, 0xc1, 0x5a,
	0xa2, 0x18, 0x6c, 0x05, 0x97, 0x9c, 0x5e, 0x3a, 0x1a, 0x4e, 0xd8, 0x62, 0xd4, 0x6d, 0x07, 0x18,
	0xa3, 0xf0, 0x22, 0xed, 0xb3, 0x7f, 0x13, 0x68, 0x8d, 0x78, 0xc4, 0xc5, 0x57, 0x4c, 0x12, 0x2f,
	0x40, 0x6a, 0x41, 0x83, 0xc7, 0x89, 0xf4, 0x24, 0x5a, 0xa4, 0x47, 0xfa, 0x26, 0xcb, 0x21, 0x6d,
	0x01, 0x11, 0x56, 0xb5, 0x47, 0xfa, 0x17, 0x8c, 0x88, 0x14, 0x05, 0x96, 0xa1, 0x51, 0x90, 0xa2,
	0xa5, 0x55, 0xd3, 0x68, 0xa9, 0x72, 0x6c, 0xbd, 0x55, 0x28, 0x1f, 0xac, 0x0b, 0x75, 0x96, 0x43,
	0xda, 0x05, 0xd3, 0xc7, 0x7d, 0xb8, 0xc2, 0xe9, 0xbd, 0x55, 0xef, 0x91, 0x7e, 0x93, 0x3d, 0xe2,
	0xd4, 0xb7, 0xf5, 0x92, 0xe4, 0xc0, 0x85, 0x6f, 0x35, 0xb4, 0x2f, 0xc7, 0xf6, 0x0f, 0x68, 0xb9,
	0xa9, 0x88, 0x7f, 0xab, 0x2c, 0x32, 0x54, 0x4b, 0x18, 0x8c, 0x13, 0x86, 0x03, 0x3c, 0x77, 0x57,
	0x6b, 0xf4, 0x77, 0x11, 0xfa, 0xee, 0x21, 0x94, 0xab, 0x35, 0xa5, 0x50, 0x93, 0xe1, 0x46, 0x33,
	0x18, 0x4c, 0xd9, 0x45, 0xe2, 0xea, 0x79, 0x62, 0xa3, 0x84, 0xb8, 0x76, 0x42, 0xfc, 0x09, 0x4c,
	0x87, 0x07, 0xe3, 0x58, 0x8a, 0x87, 0x73, 0x8c, 0x1b, 0x5d, 0x75, 0x56, 0x4f, 0x0e, 0xed, 0x04,
	0xc0, 0xe1, 0x01, 0xc3, 0x5f, 0x3b, 0x4c, 0x24, 0xfd, 0x00, 0x66, 0xc4, 0x03, 0x07, 0xf7, 0x18,
	0xa9, 0xf8, 0x67, 0x37, 0x57, 0x83, 0xc2, 0xe0, 0x07, 0x4e, 0xe6, 0x64, 0x8f, 0xd7, 0xe8, 0x6b,
	0xa8, 0x7b, 0x1b, 0xbe, 0x8b, 0x65, 0x36, 0xd6, 0x0c, 0x95, 0xf5, 0xe9, 0xfd, 0xad, 0x92, 0xab,
	0xe3, 0x9b, 0x70, 0x71, 0x3f, 0x1e, 0x7e, 0x9b, 0x74, 0x2a, 0xd4, 0x84, 0xda, 0x74, 0xf6, 0x65,
	0xde, 0x21, 0xa9, 0xf5, 0xfd, 0x8e, 0xcd, 0x3a, 0xd5, 0xd4, 0x3d, 0x66, 0x6c, 0xce, 0x3a, 0x46,
	0x6a, 0x2e, 0xee, 0x66, 0xd3, 0x51, 0xa7, 0x76, 0xf3, 0xc7, 0x80, 0x46, 0xa6, 0x8b, 0x7e, 0x86,
	0xe6, 0x04, 0x65, 0x3a, 0xd9, 0x5d, 0x42, 0x5f, 0x1d, 0xc9, 0xcd, 0xca, 0xea, 0xbe, 0x3d, 0x3a,
	0x2d, 0xae, 0xaa, 0x5d, 0xa1, 0xb7, 0x00, 0xf3, 0x2d, 0xc6, 0xae, 0x14, 0xe8, 0x6d, 0xfe, 0x3b,
	0xc1, 0x35, 0xa1, 0x23, 0x68, 0x3b, 0xdc, 0xf3, 0x5d, 0x14, 0x7b, 0x14, 0x0e, 0x0f, 0xe8, 0x9b,
	0xd3, 0x9e, 0xe5, 0x69, 0x9e, 0x34, 0x53, 0x4d, 0xcc, 0xae, 0x5c, 0x13, 0xba, 0x80, 0x97, 0xf9,
	0xea, 0xe8, 0xcd, 0x51, 0xab, 0x4a, 0xdf, 0x1d, 0x45, 0x9c, 0x2c, 0xd7, 0x13, 0x59, 0xf1, 0xcf,
	0x50, 0x6c, 0x3c, 0x19, 0xf2, 0xd8, 0xae, 0xd0, 0x21, 0x98, 0x2e, 0x4a, 0xa5, 0x95, 0x9e, 0xd7,
	0x5f, 0x9e, 0x63, 0x0c, 0x97, 0x45, 0x35, 0xc7, 0x77, 0x8b, 0x8f, 0xa9, 0x34, 0xcd, 0xf0, 0x0a,
	0x5e, 0xf8, 0x38, 0xd8, 0x86, 0xea, 0x4b, 0x49, 0xf4, 0xaf, 0xb1, 0x20, 0xcb, 0xba, 0x32, 0x3e,
	0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x15, 0xaf, 0x43, 0x6b, 0x04, 0x00, 0x00,
}
